### ISSUE TITLE
Issue installing package from dappstore

### ISSUE THREAD

**Issue by AlanDevOps** [dappnode/DAppNodePackage-web3signer#22]
**Describe the bug**

**To Reproduce**

Install the package from dappstore while on dappnode version v0.2.64

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/86825716/209568588-dfc37c6d-cc06-41bc-a6ed-190c421bce9c.png)

**DAppNode version:**

- Package version: 
- OS: 
- Browser 

**Additional context**

**Comment by hpanon** [comment]
![image](https://user-images.githubusercontent.com/105939904/209569786-addc9b9c-5c44-43da-b899-19fd8a8d4a48.png)

**Comment by eduadiez** [comment]
are you using ipfs in local or remote mode? 

http://my.dappnode/#/system/repository

could you try using IPFS in remote mode?

**Comment by AlanDevOps** [comment]
> are you using ipfs in local or remote mode?
> 
> http://my.dappnode/#/system/repository
> 
> could you try using IPFS in remote mode?

Currently on local, switching to remote let it download, and is currently running as expected.

**Comment by hpanon** [comment]
Worked. At least installed it :)

**Comment by mfw78** [comment]
I actually don't think this should be closed, or at least there should be a link to an issue to track IPFS in Local mode.

I'm having the exact same problem, using IPFS in local mode. I have _pinned_ the package, and it's confirmed downloaded to the local IPFS node, so there should be absolutely no issues with connectivity, yet it still fails in the same style.
